trigger:
  branches:
    include:
      - main  # Or specify your desired branch

pool:
  vmImage: 'macos-latest'  # Or choose the appropriate agent for your platform (e.g., ubuntu-latest for Linux)

steps:
  - script: echo '##[command]sudo gem install cocoapods'  # Install CocoaPods for iOS
    displayName: 'Install CocoaPods'

  - script: |
      mkdir deployment
      cd deployment
      wget https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.10.1-stable.zip
      unzip flutter_macos_3.10.1-stable.zip
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter doctor
    displayName: 'Install Flutter'

  - script: flutter pub get
    displayName: 'Get Flutter dependencies'

  - script: flutter --version  # Display Flutter version
    displayName: 'Show Flutter version'

  - script: flutter build ios --release --no-codesign
    displayName: 'Build iOS app'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/build/ios/iphoneos/Runner.app'
      ArtifactName: 'iOS App'
      publishLocation: 'container'

  - script: flutter build apk --release
    displayName: 'Build Android app'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/build/app/outputs/apk/release/app-release.apk'
      ArtifactName: 'Android App'
      publishLocation: 'container'
